SELECT *
FROM SALES.SALES_ORDER_DETAIL

select special_offer_id, sum(unit_price) as "soma"
from sales.sales_order_detail
GROUP BY special_offer_id

SELECT FIRST_NAME, COUNT(FIRST_NAME) AS "CONTAGEM"
FROM PERSON.PERSON
GROUP BY FIRST_NAME

SELECT COLOR, AVG(LIST_PRICE) AS "PRECO"
FROM PRODUCTION.PRODUCT
WHERE COLOR = 'SILVER'
GROUP BY COLOR