SELECT *
FROM SALES.SALES_ORDER_DETAIL
-- SUM
select special_offer_id, sum(unit_price) as "soma"
from sales.sales_order_detail
GROUP BY special_offer_id

-- COUNT
SELECT FIRST_NAME, COUNT(FIRST_NAME) AS "CONTAGEM"
FROM PERSON.PERSON
GROUP BY FIRST_NAME

-- AVG
SELECT COLOR, AVG(LIST_PRICE) AS "PRECO"
FROM PRODUCTION.PRODUCT
WHERE COLOR = 'SILVER'
GROUP BY COLOR

SELECT MIDDLE_NAME, COUNT(FIRST_NAME) AS "QUANTIDADE" FROM PERSON.PERSON GROUP BY MIDDLE_NAME;


SELECT PRODUCT_ID, AVG(ORDER_QTY) AS "MEDIA" FROM SALES.SALES_ORDER_DETAIL GROUP BY PRODUCT_ID


SELECT TOP 10 PRODUCT_ID, SUM(LINE_TOTAL) FROM SALES.SALES_ORDER_DETAIL GROUP BY PRODUCT_ID ORDER BY SUM(LINE_TOTAL) DESC;






SELECT PRODUCT_ID, COUNT(PRODUCT_ID), AVG(ORDER_QTY) AS "MEDIA" FROM PRODUCTION.WORKORDER  GROUP BY PRODUCT_ID;

