-- 1EX:
SELECT NOME FROM PERSON.PERSON WHERE NOME HAVING 10 RESULTS;
SELECT FIRST_NAME, COUNT(FIRST_NAME) AS "QUANTIDADE" 
FROM PERSON.PERSON GROUP BY FIRST_NAME
HAVING COUNT(FIRST_NAME)>10

-- 2EX:
SELECT PRODUCT_ID, SUM(LINE_TOTAL) AS "TOTAL" 
FROM PRODUCT_DETAIL GROUP BY PRODUCT_ID HAVING SUM(LINE_TOTAL) BETWEEN 162000 AND 500000;




SELECT NAME_PERSON, COUNT(NAME_PERSON) AS "QUANTIDADE" 
FROM PERSON.PERSON WHERE TITLE LIKE "MR.%"

SELECT FIRST_NAME, COUNT(FIRST_NAME) AS "QUANTIDADE" FROM
PERSON.PERSON WHERE TITLE = 'MR.'
GROUP BY FIRST_NAME
HAVING COUNT(FIRST_NAME)>10


-- DESAFIO

SELECT STATE_PROVIENCE_ID, COUNT(STATE_PROVIENCE_ID) AS "QUANTIDADE" 
FROM PERSON.ADRESS
GROUP BY STATE_PROVIENCE_ID
HAVING COUNT(STATE_PROVIENCE_ID) > 1000

SELECT PRODUCT_ID, AVG(LINE_TOTAL) FROM SALES.SALES_ORDER_DETAIL
GROUP BY PRODUCT_ID
HAVING AVG(LINE_TOTAL) < 1000000


-- DESAFIO COM AS
-- EX.:1
SELECT TOP 10 FIRST_NAME AS "PRIMEIRO_NOME", LAST_NAME AS "SOBRENOME" FROM PERSON.PERSON

-- EX.:2
SELECT TOP 10 PRODUCT_NUMBER AS "NUMERO DO PRODUTO" FROM PRODUCTION.PRODUCT
-- EX.:3
SELECT TOP 10 UNIT_PRICE AS "PREÇO UNITÁRIO" FROM SALES.SALES_ORDER_DETAIL