-- Existem 3 tipos de joins: INNER JOIN, OUTER JOIN, SELF JOIN

-- EX1.:
SELECT P.BUSINESS_ENTITY_ID, P.FIRST_NAME, P.LAST_NAME, PE.EMAIL_ADDRESS
FROM PERSON.PERSON P
INNER JOIN PERSON.EMAIL_ADDRESS PE ON P.BUSINESS_NETITY_ID = PE.BUSINESS_ENTITY_ID

-- DESAFIO 1

SELECT PP.BUSINESS_ENTITY_ID, PT.NAME, PT.PHONE_NUMBER_TYPE_ID, PP.PHONE_NUMBER
FROM PERSON.PERSON_PHONE PP
INNER JOIN PERSON.PHONE_NUMBER_TYPE PT ON PP.PHONE_NUMBER_TYPE_ID = PT.PHONE_NUMBER_TYPE_ID

-- DESAFIO 2

SELECT TOP 10 PA.ADDRESS_ID, PA.CITY, PS.STATE_PROVIENCE_ID, PS.STATE_NAME
FROM PERSON.ADRESS PA
INNER JOIN PERSON.STATE_PROVIENCE PS ON PS.STATE_PROVIENCE_ID = PA.STATE_PROVIENCE_ID