-- DESCOBRIR QUANTAS PESSOAS TEM UM CARTÃO DE CREDITO REGISTRADO
SELECT * FROM PERSONS.PERSON
LEFT JOIN SALES.PERSON_CREDIT_CARD PC ON PP.BUSINESS_ENTITY_ID = PC
WHERE PC.BUSINESS_ENTITY_ID IS NULL
-- RESULTADOS COM INNER JOIN: 19118
-- RESULTADOS COM LEFT JOIN: 19972
